export const REQUEST_API_STARTED='REQUEST_API_STARTED';
export const REQUEST_API_FAILED='REQUEST_API_FAILED';
export const REQUEST_API_SUCCESS='REQUEST_API_SUCCESS';

export const ADD_TO_FAVORITES='ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES='REMOVE_FROM_FAVORITES';
//Favorite